language: java

jdk:
  - openjdk14
  - openjdk11
  - openjdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: V+Jp7wB9WhTizjqELV6chKUFSEny3nSvV7pdzf41AvPbt25JcbbCqkUN5hzNW4SYBVYyLr+xDf4aHVUOUL77a5Uq9NwZHSMmZGfdUXDg1LJGONajRmTqszkNq/+LeniRZ45JVqWOABLxpjKYbdTXddaV/HR7VWFjOCZh4KMtg0RFjaS80VoF38Nzu20jjXY5f3St/wHSPrx0BiG3Y88rsolBJexAw/3zrIW/58TyTz405qKYYZd1o3SaSS3685yr/yUnSyh/o7oI45lU4/h1kHxAUPS63cHQLmr7dyTjeMiA7e5Cql+O60sjdtk1wC4ceeWxbNbZP4kNAZn9TwuG6F9No3Bxf21APGmudd9riUulQG7/S8jEeqIGmXyZmtp0oOOtcEbFKObccJiiwu949ul7CrkvtJ3Zy/SlYm4f+aOV/oCxetuRSFCBkYYaf/yCFuWvFoB+TBSMdlQQTzDGERK6ddFeC/epZIgVynyHbjuYPc8LgyHwvye8p1HoHatYxo8LO1igYyEyZ+3V25ETM34rfdNTjC4IhnyD8swTxSduxOKOjj3SCDKAC3h0/muhHwTfmkA2JS7yfZUqOpMfZDAxgPwNVVXxyqcsaOtTuJu0aP9OV5m0d+pkZs2pgkL5NyyouUuCp4Q+HXKIBrM/JlYeKWKyeJZRHiRlOZn8bFg=
    - secure: nqLn/Yi384V2rIhKh85SLJPJKnwWw7OpStFDkXFsJwvKXsGwQ/2LkgdSHBUcZwBwNKkL7aM577afgh7tSyvSxggeXhjUNNUjVKQQw5WiHKRLsC42wmcFzvjmeBcSo6UZpbBeyrwqeSOqA/WKfprB3vewKNVSfG66peyK5U+yE20+qX5A+QL+TzSoWXL1T2dswdX+rr2ekpcSC9J9PZAv8NZ1XtnH+oJgfZw9EawbUr4UX4h+akI79qul8oGNvYoMYng7WP4hGvsiDHLNq4MckllA4o0EucFkzqAzoNOQ2qx5gmznIlTj2S7IDNNql7F+sqDZNzcP7BeZHdmvN7m4yV1f4fCIs7bGAAfbJWj02QQKL720Yf1V+cFjQN0hQwRILAnbrD1tSCdt2B+mxXh2lxE7HvybJjwPS5SDb+bSlTg7S+qSFr9yWuBHEtVNE8mFJ23Azaxw8e0gSStY9vbM688SJnkqmGdCkDA2KmnNynvbzu0jzRJlNNfhjeWDBj0H77KlxTGBf9IOVrwEdFkEfLfcyAEsGnTd/KDKeidb7JN8LJ71V5gnO64DHc+9phsHBb7qao2bFrDrJSQpFt/xFN5wFuUxe9tqL3UFpODx+XX9imGCSxhbZca0L+aP/eoaEc2zfOjAMYShMfvVdM0i/kd3IYOjNeim1fyZzXk31LQ=
